### ISSUE TITLE
An unknown operator will provide a result of true instead of an error

### ISSUE THREAD

**Issue by rsdmike** [diegoholiveira/jsonlogic#26]
Using rule: `{"notanoperator": [1, 1]}`
and data: `{}`
on the web playground( http://jsonlogic.com/play.html) appropriately yields:`Unrecognized operation notanoperator`

However using this package results in a successful evaluation with a result of `true`.

Using module: `github.com/diegoholiveira/jsonlogic v2.2.0+incompatible`

**Comment by rsdmike** [comment]
It looks like this should be handled -- but when trying to set module to v2.4.0 i'm getting an "unknown revision error"

**Comment by rsdmike** [comment]
i remember now -- you need to tag your release with a "v" prefix. You're last version that had that was v2.2.0 and the latest versions do not have the "v" prefix. If you add that to them -- that will make them go module compatible.

**Comment by lucianomagrao** [comment]
I fixed the release names and tags.

Thanks
