### ISSUE TITLE
Invalid evaluation

### ISSUE THREAD

**Issue by fifthaxe** [diegoholiveira/jsonlogic#32]
Hi contributors & users,

I am facing a bug with the following data & logic :

x Data :
{} or whatever data without a matching var
x Logic :
{"and":[{"<":[{"var":"foo"},"bar"]}]}
x Evaluation : true

You can play with the bug here : https://play.golang.org/p/1fBwpHNhxKk

What's funny is that if you change the greater for a lower, evaluation becomes falsy. In both case it should be false (as verified on jsonlogic.com playground) since there is no matching var in the data.

Thanks

**Comment by fifthaxe** [comment]
Should be fixed in #33

**Comment by diegoholiveira** [comment]
Thanks for the contribution: https://github.com/diegoholiveira/jsonlogic/releases/tag/v2.5.1
