### ISSUE TITLE
 invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

### ISSUE THREAD

**Issue by hexadecy** [diegoholiveira/jsonlogic#35]
## Step-by-step
1. I took the first example from the readme.
2. Created a module: `go mod init myNewProject`
3. Edited my `go.mod`
```
module myNewProject

go 1.13

require (
        github.com/diegoholiveira/jsonlogic/v2 v2.5.2
        github.com/mitchellh/copystructure v1.0.0 // indirect
)
```
4. Then: `go get`
```shell
require github.com/diegoholiveira/jsonlogic: version "v2.5.2" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

## Possible solutions
- change your module name in `go.mod` to `github.com/diegoholiveira/jsonlogic/v2`
   - But you have to delete tag that don't begin with `v`
- or change to `/v3` and create a new `v3.0.0` tag.

**Comment by hexadecy** [comment]
I also try with:
`require github.com/diegoholiveira/jsonlogic/v2 v2.5.2`

```
go: github.com/hortau/jsonlogic/v2@v2.5.2: go.mod has non-.../v2 module path "github.com/diegoholiveira/jsonlogic" (and .../v2/go.mod does not exist) at revision v2.5.2
```

**Comment by diegoholiveira** [comment]
Hi mate

Can you share my details about your setup? It looks like it's not a problem with the library it self, but let's debug it first before reaching any conclusions.

@lucianomagrao did you see any error like this while migrating from deps to go mod?

**Comment by lucianomagrao** [comment]
I think we need to add `/v2` to our module name, but we have to delete old tags without `v` and deleting this will break something for sure.

So I think the best solution is to delete all tags after `v2.3.1` (because its impossible to use gomodules to use then), add `/v3` to module name, and create `v.3.0.0``

Versions from `v2.4.0...v2.5.2` are only usable if you refer to it by commit. Like `go get github.com/diegoholiveira/jsonlogic@42d65836c4463d0d51a8f8bd7e79e93e47d97890`, so nothing changes for anyone that's using it.

**Comment by hexadecy** [comment]
go1.13.12 darwin/amd64
We are all using go mod.

@lucianomagrao yes `/v3` will be the safest way to go.

**Comment by diegoholiveira** [comment]
> I think we need to add `/v2` to our module name, but we have to delete old tags without `v` and deleting this will break something for sure.

@lucianomagrao are you talking about change our go.mod to be like this:

```
module github.com/diegoholiveira/jsonlogic/v2

go 1.13

require (
	github.com/mitchellh/copystructure v1.0.0
	github.com/stretchr/testify v1.6.1
)
```

I still did get what the problem is. I got it working here just fine, take a look:

[![asciicast](https://asciinema.org/a/347264.svg)](https://asciinema.org/a/347264)

**Comment by lucianomagrao** [comment]
Your go get downloaded the latests version without `go mod`(v.2.3.1) because versions after that include `go.mod` and it's not using `/v2` in module name, so it's invalid version.

try to run: `go get github.com/diegoholiveira/jsonlogic@v2.4.1`

**Comment by hexadecy** [comment]
You also need to rename the test file:
"github.com/diegoholiveira/jsonlogic/internal"	to	"github.com/diegoholiveira/jsonlogic/v2/internal"

**Comment by diegoholiveira** [comment]
Done
