### ISSUE TITLE
0 divided by any number returning denominator instead of 0

### ISSUE THREAD

**Issue by deepchenna** [diegoholiveira/jsonlogic#36]
Please refer to the old issue for more details.

https://github.com/diegoholiveira/jsonlogic/issues/28

**Comment by diegoholiveira** [comment]
Please use the latest version (v3) and check if issue is solved. I do think you may be using an older version.

**Comment by diegoholiveira** [comment]
@deepchenna did you check it up if the bug exists in v3?
