### ISSUE TITLE
Error if var is missing from data

### ISSUE THREAD

**Issue by Makpoc** [diegoholiveira/jsonlogic#37]
Hello,

I seem to hit a case where the library is returning an error when a property, that is in the "logic" but not in the "data". Below is an example program to reproduce the issue.

```go
package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/diegoholiveira/jsonlogic"
)

func main() {
	logic := strings.NewReader(`{"logic":{"and":[{"!":{"var":"var_not_in_data"}}]}}`)
	data := strings.NewReader(`{"some_key": "value"}`)

	var result bytes.Buffer
	err := jsonlogic.Apply(logic, data, &result)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Println(result.String())
}
```

And here's the output:

```
interface conversion: interface {} is nil, not []interface {}

Process finished with exit code 1
```

If I add the `var_not_in_data` to the `data` object it evaluates the expression correctly.

Edit Note: It used to panic with version 2, it just returns the error now with v3

**Comment by diegoholiveira** [comment]
@Makpoc can you provide a valid test case?

`logic := strings.NewReader(`{"logic":{"and":[{"!":{"var":"var_not_in_data"}}]}}`)`

This jsonlogic is not valid since `logic` it's not a valid json logic command

**Comment by Makpoc** [comment]
Right, sorry. Just remove the `logic` level:
```go
package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/diegoholiveira/jsonlogic/v3"
)

func main() {
	logic := strings.NewReader(`{"and":[{"!":{"var":"var_not_in_data"}}]}`)
	data := strings.NewReader(`{"some_key": "value"}`)
	//data := strings.NewReader(`{"var_not_in_data": ""}`) // works with this line

	var result bytes.Buffer
	err := jsonlogic.Apply(logic, data, &result)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Println(result.String())
}
```

**Comment by julianogalgaro** [comment]
@Makpoc I think your logic is not valid yet. I think the `"!"` operator needs an array.

```
package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/diegoholiveira/jsonlogic/v3"
)

func main() {
	logic := strings.NewReader(`{"and":[{"!":[{"var":"var_not_in_data"}]}]}`)
	data := strings.NewReader(`{"some_key": "value"}`)  // results true
	//data := strings.NewReader(`{"var_not_in_data": ""}`) // results false

	var result bytes.Buffer
	err := jsonlogic.Apply(logic, data, &result)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Println(result.String())
}
```

**Comment by Makpoc** [comment]
Thanks for getting back to me on this.

I tried this logic on jsonlogic.com's playground and it validated correctly.

According to their definition it can take either an array or a single argument: http://jsonlogic.com/operations.html#logic-and-boolean-operations

> Note: unary operators can also take a single, non array argument:

**Comment by diegoholiveira** [comment]
I'm planning to investigate this issue in the next days. Also, I'll do a profound refactoring of how we deal with errors, to make it clear what's wrong with your logic, the current state will not good to debug problems with your logic.

**Comment by Makpoc** [comment]
Hi. Do you have any update on this?

I'm trying out https://ukrbublik.github.io/react-awesome-query-builder/ as a frontend and it seems to generate the jsonlogic object with the single argument syntax.

**Comment by diegoholiveira** [comment]
Hi @Makpoc, currently I'm working in another things and while is in my todo list here, I didn't check it out.

what do you think about provide a PR to fix it? It would be awesome :)

**Comment by Makpoc** [comment]
I can indeed try and do that. I debugged the issue a little when I submitted it initially, but got lost in the deep nesting. I'm not too familiar with jsonlogic, but it might be a good time to learn it :)

Any hints on where to start would be awesome!

**Comment by diegoholiveira** [comment]
@Makpoc check the PR #37 please, it may fix your issue.

**Comment by Makpoc** [comment]
Sorry for the late response. This change fixes the error, but returns the wrong response.

The following logic:
```
{"and":[{"!":{"var":"var_not_in_data"}}]}
```

returns `false` for `{"some_key": "value"}` but it should return `true`.

**Comment by diegoholiveira** [comment]
@Makpoc can you check again please?

**Comment by Makpoc** [comment]
Awesome! Seems to be working correctly now.

I'd suggest adding one more test:

```go
func TestUnaryOperationNegative(t *testing.T) {
	logic := strings.NewReader(`{"and":[{"!":{"var":"var_not_in_data"}}]}`)
	data := strings.NewReader(`{"some_key": "value", "var_not_in_data": "but_it_is" }`)

	var result bytes.Buffer
	assert.Nil(t, Apply(logic, data, &result))

	assert.JSONEq(t, `false`, result.String())
}
```
