### ISSUE TITLE
Is it possible to add custom operator?

### ISSUE THREAD

**Issue by huangjunwen** [diegoholiveira/jsonlogic#39]
I think it would be very useful if adding custom operator is supported.

Like: http://jsonlogic.com/add_operation.html

**Comment by diegoholiveira** [comment]
@huangjunwen sure, if you add it, we can remove some custom things that we add it to solve internal problems. Can you provide a PR? It will be awesome :)

**Comment by huangjunwen** [comment]
@diegoholiveira after a few days' investigation and experiments, i end up reinvent the [wheel](https://github.com/huangjunwen/jsonlogic-go) myself to fulfill this and some other requirments as well. Much inspiration from your library though :-) Thanks a lot!

**Comment by diegoholiveira** [comment]
awesome work @huangjunwen 

I'll close this issue
