### ISSUE TITLE
Panic: interface conversion: interface {} is nil, not float64

### ISSUE THREAD

**Issue by dukeNuken3D** [diegoholiveira/jsonlogic#40]
Hi,

Reaching a bug when applying the following logic/data :

- logic : {"or": [{"<=": [100, {"var": "ANY_VAR_EXCEPT_temperature"}, 200]}]}

-  data : {"temperature": 12}

Here is a playground showing the problem : https://play.golang.org/p/cznGTSvuSgG

Can someone have a look ?

Regards,

**Comment by diegoholiveira** [comment]
> Hi,
> 
> Reaching a bug when applying the following logic/data :
> 
> * logic : {"or": [{"<=": [100, {"var": "ANY_VAR_EXCEPT_temperature"}, 200]}]}
> * data : {"temperature": 12}
> 
> Here is a playground showing the problem : https://play.golang.org/p/cznGTSvuSgG
> 
> Can someone have a look ?
> 
> Regards,

Change your code to be like this:


```go
package main

import (
	"bytes"

	"github.com/davecgh/go-spew/spew"
	"github.com/diegoholiveira/jsonlogic/v3"
)

var _ = spew.Dump

func main() {
	var result bytes.Buffer
	
        jsonlogic.Apply(
		bytes.NewReader([]byte("{\"or\": [{\"<=\": [100, {\"var\": \"ANY_VAR_EXCEPT_temperature\"}, 200]}]}")),
		bytes.NewReader([]byte("{\"temperature\": 12}")),
		&result,
	)
	spew.Dump(result.String())
}
```
