### ISSUE TITLE
validateJsonLogic not exported

### ISSUE THREAD

**Issue by Evgenus** [diegoholiveira/jsonlogic#44]
Hi. I need validateJsonLogic in my code because I decode a bunch of rules from a big JSON structure. And I want to check them when they are already `interface{}`.

Please export it

**Comment by diegoholiveira** [comment]
It would be possible to use the [IsValid](https://github.com/diegoholiveira/jsonlogic/blob/master/validator.go#L9) method?

**Comment by Evgenus** [comment]
> It would be possible to use the [IsValid](https://github.com/diegoholiveira/jsonlogic/blob/master/validator.go#L9) method?

Yes, it works that way for me now, but I have to serialize my rule definition back to a string. And then `IsValid` deserializes it inside. Doesn't look pretty.

**Comment by diegoholiveira** [comment]
Can you open an PR exposing it?
