### ISSUE TITLE
Custom operators are not examined by isOperator func which always results in invalid for rules with custom operators 

### ISSUE THREAD

**Issue by zachcheh** [diegoholiveira/jsonlogic#47]

**Comment by zachcheh** [comment]
Here is an example.
https://go.dev/play/p/1nPCQU2hFFA

**Comment by diegoholiveira** [comment]
Hey @zachcheh . Thanks to raise this issue. Would you mind in open an PR with a fix?

@lucianomagrao FYI

**Comment by zachcheh** [comment]
Happy to do it! Below is the PR. Let me know if you would like any other changes.
https://github.com/diegoholiveira/jsonlogic/pull/48
