### ISSUE TITLE
Unable to use V2 or V3 versions

### ISSUE THREAD

**Issue by lenny-goodell** [diegoholiveira/jsonlogic#49]
As pointed out in #35 your go.mod module name needs `/v2` 
This looks to be corrected for `V3` but it is very strange that your go.mod for `V3` references your own module as `github.com/diegoholiveira/jsonlogic v2.3.1+incompatible`
 
https://github.com/diegoholiveira/jsonlogic/blob/v3.0.0/go.mod#L6

We are using Go 1.16 and 1.17 which is not allowing us to use any thing higher than `github.com/diegoholiveira/jsonlogic v1.0.1-0.20200220175622-ab7989be08b9` in Edgex Foundry here:

https://github.com/edgexfoundry/app-functions-sdk-go/blob/main/go.mod#L7

**Comment by diegoholiveira** [comment]
Sorry for take so long to take a look in this. Can you try again? I fix the `go.mod`.

**Comment by lenny-intel** [comment]
@diegoholiveira , Yes, that fixes it so we can now use v3 versions. Thanks!
