### ISSUE TITLE
Less than operator returns true with strings instead of false

### ISSUE THREAD

**Issue by GeorgeD19** [diegoholiveira/jsonlogic#50]
To Reproduce

1. Run the following code

```
package main

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/diegoholiveira/jsonlogic/v3"
)

func main() {
	logic := strings.NewReader(`{"<": ["abc", 3]}`)
	data := strings.NewReader(`{}`)

	var result bytes.Buffer

	jsonlogic.Apply(logic, data, &result)

	fmt.Println(result.String())
}
```

Expected
false

"abc" is not less than 3. 
Using the same logic / data here https://jsonlogic.com/play.html will return the expected result.

![Screenshot 2022-02-25 at 12 31 12](https://user-images.githubusercontent.com/6735386/155715631-02419fb2-cbd8-45d2-927b-20a3a9629a36.png)

Actual
true

**Comment by diegoholiveira** [comment]
Fixed in 08d60112ba3e0e666682f677a0c43899284013a3
