### ISSUE TITLE
Error Operation Equals with Nulls

### ISSUE THREAD

**Issue by jsanabria-ml** [diegoholiveira/jsonlogic#60]
Error Operation Equals with nulls, which both parameters are _**null**_ gives me a **false** response `logic := strings.NewReader('{"==": [null, null]}');` but from the operations page [operations](https://jsonlogic.com/operations.html) I get a **true** response

Checking, there is a condition in the function Equals, indicating that if any is nil, it returns _false_; which I don't see is the right solution

**Comment by diegoholiveira** [comment]
Can you provide a PR fixing it? :)
