### ISSUE TITLE
Operation with null data values gives incorrect results

### ISSUE THREAD

**Issue by alvery** [diegoholiveira/jsonlogic#61]
**Rule:**
`{
      "!=": [
        {
          "var": "before"
        },
        null
      ]
    }`
 **Data:**
 `
 {"before": null, "after": "text"}
 `
 
 This gives true, found some workaround for now to fix the problem (using comparing <> operators).

**Comment by diegoholiveira** [comment]
can you provide a PR fixing it?

**Comment by reb-felipe** [comment]
PR: https://github.com/diegoholiveira/jsonlogic/pull/64
