### ISSUE TITLE
get the jsonlogic evaluated back from the method that apply

### ISSUE THREAD

**Issue by FlorianRuen** [diegoholiveira/jsonlogic#65]
Hey @diegoholiveira,

I'm using this library to apply a jsonlogic built from my UI (using https://react-querybuilder.js.org), but for my use case, I need to help users to "debug" if the response is false

To achieve this, my idea is to print to the user, the logic applied, but I want the vars replaced directly. To be clear, instead of

```json
{
  "and":[
    { "==":[{ "var":"VariableA" }, true] },
    { "==":[{ "var":"VariableB" }, true] },
    { ">=":[{ "var":"VariableC" }, 17179869184] },
    { "==":[{ "var":"VariableD" }, "0"] },
    { "<":[{ "var":"VariableE" }, 20] }
  ]
}
```

I need

```json
{
  "and":[
    { "==":[false, true] },
    { "==":[true, true] },
    { ">=":[34359738368, 17179869184] },
    { "==":[12, "0"] },
    { "<":[14, 20] }
  ]
}
```

I haven't seen any function that can achieve this (only `solveVars` and `getVar`)
There is any way to get this result ?

Kindly

**Comment by FlorianRuen** [comment]
@diegoholiveira 
I've created a new function on a fork of your repo using `solveVars`

```go
func solveVarsBackToJsonLogic(rule, data interface{}) ([]byte, error) {
	ruleMap := rule.(map[string]interface{})
	result := make(map[string]interface{})

	for operator, values := range ruleMap {
		result[operator] = solveVars(values, data)
	}

	body, err := json.Marshal(result)

	if err != nil {
		return nil, err
	}

	return body, nil
}
```

It seems working for all my cases. Is this a good way to do it?
If so, I can do some cleaning and create a pull request on this repo

**Comment by diegoholiveira** [comment]
hi @FlorianRuen ,

It looks like a good approach, so yeah, clear it out and send me PR and I'll review it.

**Comment by FlorianRuen** [comment]
@diegoholiveira You can find the pull request right here : https://github.com/diegoholiveira/jsonlogic/pull/66 !
