### ISSUE TITLE
filter body returns error when used with array-form var

### ISSUE THREAD

**Issue by kstark** [diegoholiveira/jsonlogic#70]
Using the full `{"var": [...]}` syntax instead of the syntax sugar `{"var": "..."}` causes an error when present in a `filter` body. As an example, the following rule (adapted from the test suite) will fail:

```json
	{
		"filter": [
			{"var": ["people"]},
			{"==": [
				{"var": [".age"]},
				{"min": {"map": [
					{"var": ["people"]},
					{"var": [".age"]}
				]}}
			]}
		]
	}
```
with the data:
```json
	{
		"people": [
			{"age":18, "name":"John"},
			{"age":20, "name":"Luke"},
			{"age":18, "name":"Mark"}
		]
	}
```

I believe the cause is this line: https://github.com/diegoholiveira/jsonlogic/blob/master/vars.go#L15

**Comment by diegoholiveira** [comment]
Hey @kstark , I'll take a look on it, thanks for reporting it.

**Comment by craigpastro** [comment]
Hello! Sorry to butt in but I was playing with this example on https://jsonlogic.com/play.html and I don't think it is valid. The docs say:

> You can use filter to keep only elements of the array that pass a test. Note, that inside the logic being used to ~map~ filter, var operations are relative to the array element being worked on.

So I think you can't write the `min` operation in the filter? If I put your example in the playground it returns `[]`. If you replace the rule with
```json
{
  "filter": [
    {"var": ["people"]},
    {"==": [
      {"var": ["age"]},
      18
    ]}
  ]
}
```
then it works and returns the expected answer.

That said, the original point of `{"var": [...]}` causing an error is valid.

**Comment by kstark** [comment]
Thanks @diegoholiveira, appreciate it! And yes @craigpastro I'm not sure if the example is perfectly-conforming - it was just a case from the unit test suite that I adapted to fit.
