### ISSUE TITLE
Override custom operator not working as expected

### ISSUE THREAD

**Issue by sheenaagrawal** [diegoholiveira/jsonlogic#84]
Hello,

I am trying to override `==` and `all` operator for my implementation. To do so, my code looks like this: 

```
jsonlogic.AddOperator("==", util.EqualsOperator)
jsonlogic.AddOperator("all", util.AllOperator)
```

And then I have implementation for both the methods above that look like this:

```
func EqualsOperator(values, data interface{}) interface{} {
//implentation goes here
}

func AllOperator(values, data interface{}) interface{} {
//implentation goes here
}
```

My filter looks like this:

              {
                    "and": [
                        {
                            "==": [
                                {
                                    "var": "deploymentt.id"
                                },
                                "test123"
                            ]
                        },
                        {
                            "all": [
                                {
                                    "var": "values"
                                },
                                [               
                                  "value 1",
                                  "value 2"
                                ]
                            ]
                        }
                    ]
                }
                
I am facing a weird issue. When I run my code against this filter and sample data that should match this condition, my breakpoint for EqualsOperator hits and my override of the jsonLogic operator works. But my override of AllOperator does not work, the breakpoint never hits and it used the default jsonLogic implementation.

Can you help?

**Comment by diegoholiveira** [comment]
@sheenaagrawal the main issue is that the custom operators are being processed after some "array functions", like `all` and `filters`. I'll try to fix this issue as soon as possible, but it will take a while.

**Comment by diegoholiveira** [comment]
@sheenaagrawal will close this issue due to inactivity but feel free to reach me out if your problem persists.
